name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure docker for GCP
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Build & Push Docker Image
        run: |
          IMAGE="asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-repo/fastapi-postgres-demo"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE="asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-repo/fastapi-postgres-demo"
          gcloud run deploy fastapi-postgres-demo \
            --image $IMAGE \
            --region asia-southeast1 \
            --platform managed \
            --allow-unauthenticated \
            --add-cloudsql-instances smarttrack2project:asia-southeast1:postgres \
            --set-env-vars DATABASE_URL=$(cat .env.cloudrun)
