name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------
      # GOOGLE AUTH (WIF)
      # -------------------------
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/729893918995/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-deploy@smarttrack2project.iam.gserviceaccount.com"
          audience: "//iam.googleapis.com/projects/729893918995/locations/global/workloadIdentityPools/github-pool/providers/github-provider"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Build & Push Docker Image
        run: |
          IMAGE="asia-southeast1-docker.pkg.dev/smarttrack2project/fastapi-repo/fastapi-postgres-demo"
          docker build -t $IMAGE:$GITHUB_SHA .
          docker push $IMAGE:$GITHUB_SHA

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "fastapi-postgres-demo"
          region: "asia-southeast1"
          image: "asia-southeast1-docker.pkg.dev/smarttrack2project/fastapi-repo/fastapi-postgres-demo:$GITHUB_SHA"
