name: deploy

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: smarttrack2project
  REGION: asia-southeast1
  REPOSITORY: fastapi-repo
  SERVICE: fastapi-postgres-demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/729893918995/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-deploy@smarttrack2project.iam.gserviceaccount.com"

      - name: Configure Docker (WIF-Compatible)
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build & Push Docker image
        run: |
          IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${SERVICE}:${GITHUB_SHA}"
          echo "Building $IMAGE"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          REGION: ${{ env.REGION }}
          REPOSITORY: ${{ env.REPOSITORY }}
          SERVICE: ${{ env.SERVICE }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          region: ${{ env.REGION }}
